# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Effin' Tasty
email: feedback@effintasty.com
description: > # this means to ignore newlines until "baseurl:"
  Effin' Tasty is a cooking site dedicated to food, and the tastiest ways to
  prepare it. We have recipes and prep techniques, along with delicious pictures.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  pinkcommodity

# Build settings
markdown: kramdown

# Categories plug-in settings
category_title_prefix: ""

#Jekyll-tagging plug-in settings
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
