name: Jekyll site CI

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "0 8 * * *"

env:
  GITHUB_ACTOR: github-actions[bot]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # Standard usage
    - uses:  tielur/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        use_github_bot_for_commits: true
